name: Python Application - Assignment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies using Makefile
      run: |
        make install  # This runs 'make install' to install dependencies

    - name: Run Flask Server using Makefile
      run: |
        make run &  # This runs 'make run' to start the server in the background
        sleep 10    # Sleep to allow the server to start up

    - name: Test server response
      run: |
        curl http://127.0.0.1:5000/  # Replace with your server URL

    - name: Stop Flask Server
      run: |
        kill $(jobs -p)  # Kill the background Flask server job
