name: Python Application

on:
  push:
    branches: [main]  # Or [master] if using the master branch
  pull_request:
    branches: [main]  # Or [master] if using the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use your required Python version

    - name: Install dependencies
      run: make install  # Ensure your Makefile contains an 'install' rule

    - name: Run the application
      run: make run  # Ensure your Makefile contains a 'run' rule

    - name: Sleep for a few seconds to ensure server starts
      run: sleep 10
