name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: make install

    # Run the server
    - name: Run the app
      run: make run & sleep 10
    
    # Optionally, you can add any tests to ensure the server runs correctly
    - name: Verify server started
      run: curl http://localhost:3000/ || exit 1
