name: Python Application - Assignment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies using Makefile
      run: |
        make install  # This runs 'make install' to install dependencies

    - name: Run Flask Server using Makefile
      run: |
        make run > flask_log.txt 2>&1 &  # Start Flask server and log output
        sleep 90    # Wait for the server to fully start

    - name: Log running processes (debugging)
      run: |
        ps aux  # Check if Flask server is running

    - name: Display Flask Server Logs
      run: |
        cat flask_log.txt  # Output the Flask logs for debugging

    - name: Test server response
      run: |
        curl http://localhost:3000/  # Test server on port 3000

    - name: Stop Flask Server
      run: |
        kill $(jobs -p)  # Kill the background Flask server job
